const profilesDatas = [
  {
    id: 1,
    name: "กิตติ",
    surname: "วัฒนกูล",
    job: "Programmer",
    experience: 3,
    resumeFileName: "resume_1.jpg",
    profilePicFileName: "",
  },
  {
    id: 2,
    name: "พชร",
    surname: "บุญเรือง",
    job: "Programmer",
    experience: 5,
    resumeFileName: "resume_2.jpg",
    profilePicFileName: "",
  },
  {
    id: 3,
    name: "ธีรภัทร",
    surname: "ศรีสวัสดิ์",
    job: "Programmer",
    experience: 2,
    resumeFileName: "resume_3.jpg",
    profilePicFileName: "",
  },
  {
    id: 4,
    name: "ปรเมศวร์",
    surname: "จิตภักดี",
    job: "Programmer",
    experience: 4,
    resumeFileName: "resume_4.jpg",
    profilePicFileName: "",
  },
  {
    id: 5,
    name: "ชยพล",
    surname: "มีทรัพย์",
    job: "Programmer",
    experience: 4,
    resumeFileName: "resume_5.jpg",
    profilePicFileName: "",
  },

  {
    id: 6,
    name: "ธนวัฒน์",
    surname: "เกษมสันต์",
    job: "Graphic Designer",
    experience: 1,
    resumeFileName: "resume_6.jpg",
    profilePicFileName: "",
  },
  {
    id: 7,
    name: "จิรายุ",
    surname: "คงเดช",
    job: "Graphic Designer",
    experience: 5,
    resumeFileName: "resume_7.jpg",
    profilePicFileName: "",
  },
  {
    id: 8,
    name: "นัทธพงศ์",
    surname: "อรุณศิลป์",
    job: "Graphic Designer",
    experience: 3,
    resumeFileName: "resume_8.jpg",
    profilePicFileName: "",
  },
  {
    id: 9,
    name: "สิรวิชญ์",
    surname: "โสภา",
    job: "Graphic Designer",
    experience: 5,
    resumeFileName: "resume_9.jpg",
    profilePicFileName: "",
  },
  {
    id: 10,
    name: "ปริญญา",
    surname: "สุวรรณดี",
    job: "Graphic Designer",
    experience: 2,
    resumeFileName: "resume_10.jpg",
    profilePicFileName: "",
  },

  {
    id: 11,
    name: "ณัฐกานต์",
    surname: "ทองมาก",
    job: "Digital Marketer",
    experience: 4,
    resumeFileName: "resume_11.jpg",
    profilePicFileName: "",
  },
  {
    id: 12,
    name: "ชนิกานต์",
    surname: "ศรีเพ็ง",
    job: "Digital Marketer",
    experience: 3,
    resumeFileName: "resume_12.jpg",
    profilePicFileName: "",
  },
  {
    id: 13,
    name: "วริศรา",
    surname: "วัฒนะชัย",
    job: "Digital Marketer",
    experience: 3,
    resumeFileName: "resume_13.jpg",
    profilePicFileName: "",
  },
  {
    id: 14,
    name: "อาทิตยา",
    surname: "มงคลชัย",
    job: "Digital Marketer",
    experience: 1,
    resumeFileName: "resume_14.jpg",
    profilePicFileName: "",
  },
  {
    id: 15,
    name: "พลอยชมพู",
    surname: "อุดมเดช",
    job: "Digital Marketer",
    experience: 5,
    resumeFileName: "resume_15.jpg",
    profilePicFileName: "",
  },

  {
    id: 16,
    name: "ปาณิสรา",
    surname: "ธนบดี",
    job: "Accountant",
    experience: 2,
    resumeFileName: "resume_16.jpg",
    profilePicFileName: "",
  },
  {
    id: 17,
    name: "สุรีรัตน์",
    surname: "จงรักษ์",
    job: "Accountant",
    experience: 5,
    resumeFileName: "resume_17.jpg",
    profilePicFileName: "",
  },
  {
    id: 18,
    name: "นฤมล",
    surname: "กิตติวงศ์",
    job: "Accountant",
    experience: 5,
    resumeFileName: "resume_18.jpg",
    profilePicFileName: "",
  },
  {
    id: 19,
    name: "รัตนา",
    surname: "คำดี",
    job: "Accountant",
    experience: 3,
    resumeFileName: "resume_19.jpg",
    profilePicFileName: "",
  },

  {
    id: 20,
    name: "กมลวรรณ",
    surname: "บุญธรรม",
    job: "HR Officer",
    experience: 1,
    resumeFileName: "resume_20.jpg",
    profilePicFileName: "",
  },
  {
    id: 21,
    name: "ธิดารัตน์",
    surname: "สังข์ทอง",
    job: "HR Officer",
    experience: 2,
    resumeFileName: "resume_21.jpg",
    profilePicFileName: "",
  },
  {
    id: 22,
    name: "สุพัตรา",
    surname: "สุขเกษม",
    job: "HR Officer",
    experience: 4,
    resumeFileName: "resume_22.jpg",
    profilePicFileName: "",
  },
  {
    id: 23,
    name: "ปาณัฐชยา",
    surname: "งามสง่า",
    job: "HR Officer",
    experience: 2,
    resumeFileName: "resume_23.jpg",
    profilePicFileName: "",
  },
  {
    id: 24,
    name: "อรทัย",
    surname: "วงศ์คำ",
    job: "HR Officer",
    experience: 4,
    resumeFileName: "resume_24.jpg",
    profilePicFileName: "",
  },

  {
    id: 25,
    name: "ศุภชัย",
    surname: "ทรัพย์ประเสริฐ",
    job: "Sales Executive",
    experience: 3,
    resumeFileName: "resume_25.jpg",
    profilePicFileName: "",
  },
  {
    id: 26,
    name: "ภควัต",
    surname: "ยอดเพชร",
    job: "Sales Executive",
    experience: 5,
    resumeFileName: "resume_26.jpg",
    profilePicFileName: "",
  },
  {
    id: 27,
    name: "กฤษณะ",
    surname: "วิจิตร",
    job: "Sales Executive",
    experience: 4,
    resumeFileName: "resume_27.jpg",
    profilePicFileName: "",
  },
  {
    id: 28,
    name: "อติรุจ",
    surname: "กำเนิดดี",
    job: "Sales Executive",
    experience: 4,
    resumeFileName: "resume_28.jpg",
    profilePicFileName: "",
  },
  {
    id: 29,
    name: "เดชธร",
    surname: "แสงทอง",
    job: "Sales Executive",
    experience: 1,
    resumeFileName: "resume_29.jpg",
    profilePicFileName: "",
  },
  {
    id: 30,
    name: "อัครเดช",
    surname: "บุญญาวงศ์",
    job: "Sales Executive",
    experience: 5,
    resumeFileName: "resume_30.jpg",
    profilePicFileName: "",
  },
];

export default profilesDatas;
